apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: authz
spec:
  exportTo: ["."]
  host: authz.{{ .Release.Namespace }}.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
