"use client";
import {PlayIcon} from "@radix-ui/react-icons";
import type {Operation} from "../lib/learning";
export default function OperationForm({operation,input,onInput,identity,onIdentity,busy,disabled,onRun}:{operation:Operation;input:Record<string,unknown>;onInput:(input:Record<string,unknown>)=>void;identity:string;onIdentity:(value:string)=>void;busy:boolean;disabled:boolean;onRun:()=>void}){
 return <section className="operation-form">
  <div className="operation-address"><span className={`method ${operation.protocol}`}>{operation.protocol==='grpc'?'RPC':operation.method}</span><code>{operation.path}</code></div>
  {operation.examples&&<div className="examples">{operation.examples.map(example=><button key={example.title} className="subtle" onClick={()=>{onInput(example.input);if(example.identity)onIdentity(example.identity)}}>{example.title}</button>)}</div>}
  {operation.protocol==='graphql'?<><label>GraphQL query<textarea rows={5} spellCheck={false} value={String(input.query??'')} onChange={e=>onInput({...input,query:e.target.value})}/></label><label>Variables (JSON)<textarea rows={2} spellCheck={false} value={typeof input.variables==='string'?input.variables:JSON.stringify(input.variables??{},null,2)} onChange={e=>onInput({...input,variables:e.target.value})}/></label></>:operation.protocol==='grpc'?<div className="field-grid">{operation.fields?.map(field=><label key={field.name}>{field.name.replace(/([A-Z])/g,' $1')} <small>{field.type}</small><input aria-label={field.name} type={['double','float','int32','int64','uint32','uint64'].includes(field.type)?'number':'text'} value={String(input[field.name]??'')} onChange={e=>onInput({...input,[field.name]:e.target.type==='number'?Number(e.target.value):e.target.value})}/></label>)}</div>:operation.method==='POST'?<label>Request JSON<textarea rows={4} value={typeof input.json==='string'?input.json:JSON.stringify(input,null,2)} onChange={e=>onInput({json:e.target.value})}/></label>:<p className="form-description">This read operation needs no request body. Choose an identity and see how the mesh handles access.</p>}
  <div className="run-controls"><label>Send request as<select aria-label="Request identity" value={identity} onChange={e=>onIdentity(e.target.value)}><option value="reader">Demo reader</option><option value="admin">Demo admin</option><option value="missing">No token</option><option value="invalid">Invalid token</option><option value="custom">Custom token</option></select></label><button className="primary run-button" disabled={disabled||busy} onClick={onRun}><PlayIcon/>{busy?'Request running…':'Run this operation'}</button></div>
 </section>
}
