apiVersion: v1
kind: Service
metadata:
  name: catalog
  labels:
    {{- include "catalog.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: catalog
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      appProtocol: http
