apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    {{- include "web.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: web
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      appProtocol: http
