apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: grafana
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      appProtocol: http
