apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: payments-from-gateway
spec:
  selector:
    matchLabels:
      app: payments
  action: ALLOW
  rules:
    - from:
        - source:
            principals:
              - "cluster.local/ns/{{ .Release.Namespace }}/sa/{{ .Values.global.gateway.serviceAccount }}"
      to:
        - operation:
            methods: [GET, POST]
            ports: ["8080"]
