apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: web-local-entry
spec:
  selector:
    matchLabels:
      app: web
  action: ALLOW
  rules:
    - to:
        - operation:
            ports: ["3000"]
